In [1]:
import numpy as np

In [3]:
# ndarray.ndim
arr = np.array([[3,4,6],[0,8,1]])
dim = np.ndim(arr)
print(dim)

2


In [4]:
# ndarray.shape
shape = np.shape(arr)
print(shape)


(2, 3)


In [5]:
# ndarray.size
size = np.size(arr)
print(size)

6


In [7]:
# ndarray.dtype
arr = np.array([[3,4,6],[0,8,1]])
print(arr.dtype)

int32


In [8]:
# ndarray.itemsize
itemsize = arr.itemsize
print(itemsize)

4


In [9]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [11]:
# 0D Arrays
arr = np.array(42)
print(arr)


42


In [12]:
# 1D arrays
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [13]:
# 2D arrays
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


NUMPY ARRAY INDEXING 

In [14]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[0:5])

[1 2 3 4 5]


In [15]:
print(arr[5:])

[6 7 8]


In [16]:
print(arr[::2])

[1 3 5 7]
