In [1]:
import numpy as np

In [3]:
# ndarray.ndim
arr = np.array([[3,4,6],[0,8,1]])
dim = np.ndim(arr)
print(dim)

2


In [4]:
# ndarray.shape
shape = np.shape(arr)
print(shape)


(2, 3)


In [5]:
# ndarray.size
size = np.size(arr)
print(size)

6


In [7]:
# ndarray.dtype
arr = np.array([[3,4,6],[0,8,1]])
print(arr.dtype)

int32


In [8]:
# ndarray.itemsize
itemsize = arr.itemsize
print(itemsize)

4


In [9]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [11]:
# 0D Arrays
arr = np.array(42)
print(arr)


42


In [12]:
# 1D arrays
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [13]:
# 2D arrays
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


NUMPY ARRAY INDEXING 

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[0:5])

[1 2 3 4 5]


In [3]:
print(arr[5:])

[6 7 8]


In [4]:
print(arr[::2])

[1 3 5 7]


In [6]:
# np.where()
arr = np.array([[-1,2,-3],[4,5,-6]])
b = np.where(arr<0,"Negative","Positive")
print(b)

[['Negative' 'Positive' 'Negative']
 ['Positive' 'Positive' 'Negative']]


In [7]:
# np.around()
arr = np.array([1.09,5.55,123,0.567,25.532])
print("Input array = ",arr)
print("\nAfter Rounding:")
print(np.around(arr))
print(np.around(arr, decimals=1))
print(np.around(arr, decimals=-1))

Input array =  [  1.09    5.55  123.      0.567  25.532]

After Rounding:
[  1.   6. 123.   1.  26.]
[  1.1   5.6 123.    0.6  25.5]
[  0.  10. 120.   0.  30.]


In [8]:
# np.floor()
arr = [0.23, 5.79, 1.2, 4.24, 9.99]
print("Original array :",arr)
new_arr = np.floor(arr)
print("\nAfter using the floor function \nOutput array : ",new_arr)

Original array : [0.23, 5.79, 1.2, 4.24, 9.99]

After using the floor function 
Output array :  [0. 5. 1. 4. 9.]


In [9]:
# numpy.ceil()
arr = [0.23,5.79,1.2,4.24,9.99]
print("Original array:",arr)
new_arr = np.ceil(arr)
print("\nAfter using the ceil function \nOutput array : ",new_arr)

Original array: [0.23, 5.79, 1.2, 4.24, 9.99]

After using the ceil function 
Output array :  [ 1.  6.  2.  5. 10.]


Statistical Function


In [10]:
# mean
# 1D array
np.sum([0.5, 1.5])

2.0

In [11]:
# 2D array
np.sum([[0,1],[0,5]])

6

In [12]:
# mean
# 1D array
a = np.array([1,2,3,4,5,6,7])
np.mean(a)

4.0

In [13]:
# 2D array
a = np.array([[1,2],[3,4]])
np.mean(a)

2.5

In [14]:
# median
# 1D array
arr = [2,2,7,1,3,9,24]
print("arr : ",arr)
print("Median of array : ",np.median(arr))

arr :  [2, 2, 7, 1, 3, 9, 24]
Median of array :  3.0


In [15]:
# 2D array
arr = [[14,17,12,33,44],[15,6,27,8,19],[23,2,54,1,4]]
print("\n Median of array, axis=0 : ",np.median(arr, axis=0))
print("\n Median of array, axis=1 : ",np.median(arr,axis=1))


 Median of array, axis=0 :  [15.  6. 27.  8. 19.]

 Median of array, axis=1 :  [17. 15.  4.]


In [16]:
# np.std()
# 1D array
arr = [2,2,7,1,3,9,34]
print("arr : ",arr)
print("Standard Deviation of array : ",np.std(arr))

arr :  [2, 2, 7, 1, 3, 9, 34]
Standard Deviation of array :  10.845858797772747


In [17]:
# 2D array
arr = [[14,17,12,33,44],[15,6,27,8,19],[23,2,54,1,4]]
print("\n Standard deviation of array, axis=0 : ",np.std(arr, axis=0))
print("\n Standard deviation of array,  axis=1 : ",np.std(arr, axis=1))


 Standard deviation of array, axis=0 :  [ 4.02768199  6.3420992  17.3781472  13.73559852 16.49915823]

 Standard deviation of array,  axis=1 :  [12.44186481  7.61577311 20.27214838]
